### ISSUE TITLE
How do I build the dataset?

### ISSUE THREAD

**Issue by awkrail** [khyathiraghavi/storyboarding_data#3]
Hello,

Following the issue #2, I downloaded the data from instructables.com and snapguide.com.
Then, I removed some recipes, which do not have steps aligned with images completely (Some steps do not have images because users do not upload them.)
As a result, we could get 28196 recipes from instructables.com and 6311 snapguide.com, respectively.
This is quite different from the stats reported in the paper (https://www.aclweb.org/anthology/P19-1606.pdf).

How do I reproduce the dataset described in Table 1 in the paper? 
<img width="398" alt="スクリーンショット 2020-04-23 8 37 15" src="https://user-images.githubusercontent.com/19744782/80043806-aa025400-853d-11ea-9525-94f06dab8fcb.png">

**Comment by khyathiraghavi** [comment]
Hi, they are blogs that are actively updated. I am glad that there is more data available now. Yes, I have written few scripts to exclude recipes that do not have images for all the steps, which is a reasonable thing to do. The difference in data is due to these active updates/uploads of new information. One thing I should have done before the stats was to have ids of recipes that belonged to train/dev/val set which could have set a testbed for future improvements/comparisons.

**Comment by awkrail** [comment]
Thank you for your reply.
Is it difficult to upload train/val/test ids?

**Comment by khyathiraghavi** [comment]
I did not include the ids in the earlier version of the script. So that would not be possible now.

**Comment by awkrail** [comment]
OK, I am going to save ids as other researchers can reproduce the results. Thank you.

**Comment by awkrail** [comment]
I'd like to ask you a question (this is not related to the issue.)
Are you going to release your training scripts described in the ACL paper?
I'd like to reproduce the results, but due to a lack of information details (for example, about the implementation of FSM), I find it difficult to implement it.

**Comment by khyathiraghavi** [comment]
Hi, as discussed in the paper, I have used fsm from here: https://github.com/festvox/speech_tools
The algorithm was originally developed for building language models for limited token sets in grapheme to phoneme prediction. Please checkout the docs to install the necessary dependencies to run fsm from the link above.

**Comment by awkrail** [comment]
Thanks for the detailed information about FSM.
I'm sorry for reopening the issue.
Are the full training scripts available (training, validating, and evaluating the method)?
